name: 'Zigbee Switch Ryan'
packageKey: 'zigbee-switch-ryan'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee switch devices"
vendorSupportInformation: "https://support.smartthings.com"
