name: 'Z-Wave Electric Meter Ryan'
packageKey: 'zwave-electric-meter-ryan'
permissions:
  zwave: {}
description: "SmartThings driver for Z-Wave electric meter devices"
vendorSupportInformation: "https://support.smartthings.com"
