name: 'Z-Wave Switch Ryan'
packageKey: 'zwave-switch-ryan'
permissions:
  zwave: {}
description: "SmartThings driver for Z-Wave switch devices"
vendorSupportInformation: "https://support.smartthings.com"
